---
title: "Recommender Systems"
author: "Brad Harbans"
date: "4/21/2021"
output: html_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Your task is to analyze an existing recommender system that you find interesting. You should:

1.  Perform a Scenario Design analysis as described below. Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.

2.  Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.

3.  Include specific recommendations about how to improve the site's recommendation capabilities going forward.

4.  Create your report using an R Markdown file, and create a discussion thread with a link to the GitHub repo where your Markdown file notebook resides. You are not expected to need to write code for this discussion assignment.

## Apple Music Reccomendations

### Scenario Design Analysis

1.  Who are Apple Music's targeted users? The platform is targeted to iOS and macOS users, although apps do exists for Windows and Android.

2.  What are their key goals? The goals are to recommend music that the user would like to listen to based on the music that they listend to and based on the preferences of their friends.

3.  How can Apple Music help them accomplish these goals? Since Apple music has the musical library of the individual users, new music and the libraries of friends and family. Apple's recommendation algorithms can help to suggest music that the end user may like to listen to.

### Reverse Engineer the Reccomender

The Apple Music interface has a section called "For You". This uses Apples reccomomendation algorithm to help apple deliver music to end users that they may like.

The recommendation engine takes into account the following:

-   Hearts---\
    Hearting anything that's playing through Apple Music helps the system better tailor For You recommendations to your tastes. You can heart the following items on Apple Music by tapping the heart icon in Now Playing view: Any song in your personal library Any song available for streaming in Apple Music's catalog Songs found through search Songs played from Beats 1 and Apple Music Radio Apple-curated playlists.

-   Plays---\
    Apple Music's recommendation engine pays attention to what you actually play to help surface similar content you may find interesting. It's important to note that Apple Music's recommendation engine takes into account full plays, but discards skips.

-   Your library--- \
    Songs you've downloaded from the iTunes Store, ripped from CDs or imported into iTunes from other sources are analyzed. Your personal library data, along with any music manually added from Apple Music to your library, influences music you get exposed to in the For You section.

-   Genres and bands you're into---\
    As part of Apple Music's setup procedure, Apple asks you to tell them which songs and genres you like. This data helps the system quickly learn what you're into. ^[@idownloadblog-zibreg-2015]
    
Users can also use Siri or the application to like or dislike an artist or a specific song.

### Recommendations About how to Improve the Site's Recommendation Capabilities

Digital Trends compared Apple Music to one of its rivals, Spotify. It notes that Spotify has a better recommended playlist, Discover Weekly, that "delivers a two-hour playlist of personalized music recommendations based on your listening habits, as well as the habits of those who listen to similar artists. Playlists are often chock-full of tracks you haven’t heard before, as well as deep cuts from some of your favorite artists. Listen to a lot of Billy Eilish? Your weekly playlist might include her brother Finneas. The feature is not always on point, but it’s often impressive." ^[@bizzaco_2021]. While Apple has a similar reccomender, the author contends that it is not as impressive as Spotify's.

## References
